[package]
name = "oto-trjp"
version = "0.1.0"
authors = ["IsE"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs = "0.8.34"
encoding_rs_io = "0.1.7"
